language: ruby

matrix:
  include:
    - os: linux
      compiler: clang
      env: MAPNIK_VERSION="2.3"
    - os: linux
      compiler: gcc
      env: MAPNIK_VERSION="2.3"

before_install:
 - sudo apt-add-repository --yes ppa:mapnik/nightly-${MAPNIK_VERSION}
 - sudo apt-get update -y

install:
 - sudo apt-get -y install libmapnik=${MAPNIK_VERSION}* mapnik-utils=${MAPNIK_VERSION}* libmapnik-dev=${MAPNIK_VERSION}* mapnik-input-plugin*=${MAPNIK_VERSION}*

before_script:
 - gem install rake-compiler rake hoe rice chunky_png cairo

script:
 - make
 - make test